### ISSUE TITLE
Troubleshoot bluetooth connection between NXT and Android

### ISSUE THREAD

**Issue by wkeifenheim** [croucha/pylon-android#1]
Log ouput:

01-28 22:12:51.989  26764-26764/lejos.android D/inQuietHours﹕ Enabled: false
01-28 22:12:51.989  26764-26764/lejos.android D/inQuietHours﹕ Option: tweaks_quiet_hours_system = false
01-28 22:12:51.989  26764-26764/lejos.android D/inQuietHours﹕ Data:
01-28 22:12:51.989  26764-26764/lejos.android D/inQuietHours﹕ inQuietHours: false
01-28 22:12:51.999  26764-27281/lejos.android D/BTSend﹕ BTSend run
01-28 22:12:51.999  26764-27281/lejos.android D/LeJOSDroid﹕ about to add LEJOS listener
01-28 22:12:52.009  26764-27281/lejos.android E/LeJOSDroid NXJ log:﹕ Protocols = 2
01-28 22:12:52.009  26764-27281/lejos.android E/LeJOSDroid NXJ log:﹕ Search Param = null
01-28 22:12:52.029  26764-27281/lejos.android E/LeJOSDroid NXJ log:﹕ Searching cache file for known Bluetooth devices
01-28 22:12:52.029  26764-27281/lejos.android E/LeJOSDroid NXJ log:﹕ Found NXT 00:16:53:15:84:51 in cache file
01-28 22:12:52.029  26764-27281/lejos.android E/LeJOSDroid NXJ log:﹕ Found 1 matching NXTs in cache file
01-28 22:12:52.029  26764-27281/lejos.android E/LeJOSDroid NXJ log:﹕ Connecting to NXT 00:16:53:15:84:51 in mode 0
01-28 22:12:52.049  26764-27282/lejos.android I/NXTCommAndroid >>>>﹕ BEGIN mConnectThread
01-28 22:12:52.049  26764-27282/lejos.android W/BluetoothAdapter﹕ getBluetoothService() called with no BluetoothManagerCallback
01-28 22:12:52.069  26764-27282/lejos.android D/BluetoothSocket﹕ connect(), SocketState: INIT, mPfd: {ParcelFileDescriptor: FileDescriptor[71]}
01-28 22:13:12.570  26764-27282/lejos.android E/NXTCommAndroid >>>>﹕ Connection failure -- unable to connect to socket
    java.io.IOException: read failed, socket might closed or timeout, read ret: -1
            at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java)
            at android.bluetooth.BluetoothSocket.waitSocketSignal(BluetoothSocket.java)
            at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java)
            at lejos.pc.comm.NXTCommAndroid$ConnectThread.run(NXTCommAndroid.java:81)
01-28 22:13:12.591  26764-27281/lejos.android E/LeJOSDroid NXJ log:﹕ Failed to open NXT 00:16:53:15:84:51
01-28 22:13:12.591  26764-27281/lejos.android E/LeJOSDroid NXJ log:﹕ Failed to connect to any NXT
01-28 22:13:12.591  26764-27281/lejos.android W/dalvikvm﹕ threadid=12: thread exiting with uncaught exception (group=0x416e16f8)
01-28 22:13:12.591  26764-27281/lejos.android E/AndroidRuntime﹕ FATAL EXCEPTION: Thread-2187
    Process: lejos.android, PID: 26764
    java.lang.NullPointerException
            at lejos.android.BTSend.run(BTSend.java:54)
01-28 22:13:12.701  26764-26764/lejos.android D/LeJOSDroid﹕ onPause() closing btSend
01-28 22:13:12.701  26764-26764/lejos.android D/BTSend﹕ BTSend run loop finished and closing
01-28 22:13:14.963  26764-27281/lejos.android D/Process﹕ killProcess, pid=26764
01-28 22:13:14.963  26764-27281/lejos.android D/Process﹕ com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException:-1 java.lang.ThreadGroup.uncaughtException:-1 java.lang.ThreadGroup.uncaughtException:-1

**Comment by wkeifenheim** [comment]
http://stackoverflow.com/questions/18657427/ioexception-read-failed-socket-might-closed-bluetooth-on-android-4-3
